# Builds a proxy d3d11.dll: forwards every real export to d3d11orig.dll EXCEPT
# D3D11CreateDevice / D3D11CreateDeviceAndSwapChain, which d3d11_proxy.cpp implements
# (to install the CreateTexture2D hook). No injection — the game loads it from Win64.
$ErrorActionPreference = "Stop"
$dir = $PSScriptRoot
$SystemDll = "C:\Windows\System32\d3d11.dll"
$ProxyName = "d3d11"; $OrigName = "d3d11orig"
$exclude = @("D3D11CreateDevice", "D3D11CreateDeviceAndSwapChain")

$vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
$vsRoot = & $vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
$vcvars = Join-Path $vsRoot "VC\Auxiliary\Build\vcvars64.bat"

$dumpTxt = Join-Path $dir "exports_d3d11.txt"
cmd /c "`"$vcvars`" >nul 2>&1 && dumpbin /nologo /exports `"$SystemDll`" > `"$dumpTxt`"" | Out-Null
$lines = Get-Content $dumpTxt

$rx = [regex]'^\s*(\d+)\s+[0-9A-Fa-f]+\s+(?:([0-9A-Fa-f]{8})\s+)?(\[NONAME\]|[A-Za-z_]\w*)'
$hdr = New-Object System.Collections.Generic.List[string]
$hdr.Add("// AUTO-GENERATED by build_d3d11.ps1"); $hdr.Add("#pragma once")
$count = 0
foreach ($ln in $lines) {
    $m = $rx.Match($ln); if (-not $m.Success) { continue }
    $ord = $m.Groups[1].Value; $name = $m.Groups[3].Value
    if ($name -eq "[NONAME]") { $hdr.Add("#pragma comment(linker, `"/EXPORT:rrord$ord=$OrigName.#$ord,@$ord,NONAME`")"); $count++; continue }
    if ($exclude -contains $name) { continue }   # we implement these
    $hdr.Add("#pragma comment(linker, `"/EXPORT:$name=$OrigName.$name,@$ord`")"); $count++
}
if ($count -lt 5) { throw "Parsed only $count exports — dumpbin parse failed." }
($hdr) | Set-Content -Path (Join-Path $dir "exports_gen_d3d11.h") -Encoding Ascii
Write-Output "Generated $count d3d11 forwarders (excluded: $($exclude -join ', '))"

cmd /c "`"$vcvars`" >nul 2>&1 && cd /d `"$dir`" && cl /nologo /LD /EHsc /O2 /MT d3d11_proxy.cpp /Fe:$ProxyName.dll"
if (-not (Test-Path (Join-Path $dir "$ProxyName.dll"))) { throw "Build failed (no $ProxyName.dll)." }
Write-Output "OK d3d11.dll built."
