# Builds a proxy dxgi.dll that forwards every real export to dxgiorig.dll (a renamed copy of
# the system dxgi.dll) while running our Worker in-process. No injection. Uses linker /EXPORT
# pragmas (reliable forwarder syntax) generated from the real DLL's export table.
param(
    [string]$SystemDll = "C:\Windows\System32\dxgi.dll",
    [string]$ProxyName = "dxgi",
    [string]$OrigName  = "dxgiorig"
)
$ErrorActionPreference = "Stop"
$dir = $PSScriptRoot
$vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
$vsRoot = & $vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
$vcvars = Join-Path $vsRoot "VC\Auxiliary\Build\vcvars64.bat"

# 1) Dump the real DLL's exports
$dumpTxt = Join-Path $dir "exports.txt"
cmd /c "`"$vcvars`" >nul 2>&1 && dumpbin /nologo /exports `"$SystemDll`" > `"$dumpTxt`"" | Out-Null
$lines = Get-Content $dumpTxt

# 2) Parse exports and generate linker /EXPORT forwarder pragmas
$rx = [regex]'^\s*(\d+)\s+[0-9A-Fa-f]+\s+(?:([0-9A-Fa-f]{8})\s+)?(\[NONAME\]|[A-Za-z_]\w*)'
$hdr = New-Object System.Collections.Generic.List[string]
$hdr.Add("// AUTO-GENERATED by build_dxgi.ps1 — do not edit.")
$hdr.Add("#pragma once")
$count = 0
foreach ($ln in $lines) {
    $m = $rx.Match($ln)
    if (-not $m.Success) { continue }
    $ord = $m.Groups[1].Value
    $name = $m.Groups[3].Value
    if ($name -eq "[NONAME]") {
        $hdr.Add("#pragma comment(linker, `"/EXPORT:rrord$ord=$OrigName.#$ord,@$ord,NONAME`")")
    } else {
        $hdr.Add("#pragma comment(linker, `"/EXPORT:$name=$OrigName.$name,@$ord`")")
    }
    $count++
}
if ($count -lt 5) { throw "Parsed only $count exports — dumpbin parse failed." }
$hdrPath = Join-Path $dir "exports_gen.h"
$hdr | Set-Content -Path $hdrPath -Encoding Ascii
Write-Output "Generated $count export forwarders -> exports_gen.h"

# 3) Compile (pragmas carry the exports; no .def needed)
cmd /c "`"$vcvars`" >nul 2>&1 && cd /d `"$dir`" && cl /nologo /LD /EHsc /O2 /MT proxy.cpp /Fe:$ProxyName.dll"
$proxyDll = Join-Path $dir "$ProxyName.dll"
if (-not (Test-Path $proxyDll)) { throw "Proxy build failed (no $ProxyName.dll)." }

# 4) Validate: count forwarders to OrigName in the built DLL
$dump2 = Join-Path $dir "proxy_exports.txt"
cmd /c "`"$vcvars`" >nul 2>&1 && dumpbin /nologo /exports `"$proxyDll`" > `"$dump2`"" | Out-Null
$fwd = ((Get-Content $dump2) | Select-String -SimpleMatch "$OrigName.").Count
Write-Output ("Built {0}.dll with {1} forwarded exports (need {2})." -f $ProxyName, $fwd, $count)
if ($fwd -lt $count) { throw "Only $fwd/$count forwarders present — incomplete." }
Write-Output "OK proxy validated."
