@echo off
echo Starting RazorReaper App...
cd C:\Users\cedri\.gemini\antigravity\worktrees\RazorReaper\implement-hwid-license-system\RazorReaper
echo Building...
dotnet build
echo Running...
dotnet run -f net10.0-windows10.0.19041.0
pause
