// Cave database — dataset v1.
// Entrance coordinates compiled from community documentation (official ARK wiki cave
// pages and long-standing community guides) for ARK: Survival Evolved. All notes and
// descriptions are written in our own words. Descriptive names are used for caves that
// have no widely agreed official name (mainly Lost Island and a few Fjordur entries).
// setplayerpos entrance commands are deferred until verified in-game (field is wired
// through the model and UI, so filling them in later requires no code changes).

namespace RazorReaper.Components.Pages;

public enum CaveDifficulty
{
    Easy,
    Medium,
    Hard
}

public sealed record CaveEntry(
    string Map,
    string Name,
    string? Artifact,
    double? Lat,
    double? Lon,
    CaveDifficulty Difficulty,
    string[] Hazards,
    string Loadout,
    string Loot,
    string? SetPlayerPos = null,
    string? ImagePath = null);

public static class CaveDatabase
{
    public static readonly IReadOnlyList<string> Maps = new[]
    {
        "The Island",
        "The Center",
        "Scorched Earth",
        "Ragnarok",
        "Aberration",
        "Extinction",
        "Valguero",
        "Crystal Isles",
        "Lost Island",
        "Fjordur"
    };

    public static readonly IReadOnlyList<CaveEntry> All = new List<CaveEntry>
    {
        // ===== The Island (11) =====
        new("The Island", "Lower South Cave", "Hunter", 80.3, 53.5, CaveDifficulty.Easy,
            new[] { "Insects", "Titanoboas", "Crouch tunnels" },
            "Shotgun, bug repellant, and a torch cover it.",
            "Low-tier crates; a good first artifact run."),
        new("The Island", "Upper South Cave", "Pack", 68.2, 56.2, CaveDifficulty.Medium,
            new[] { "Insects", "Snakes", "Tight squeezes" },
            "Repellant plus a pump shotgun; mounts stay outside.",
            "Mixed crates along the artifact path."),
        new("The Island", "Central Cave", "Clever", 41.5, 46.9, CaveDifficulty.Medium,
            new[] { "Onyc swarms", "Mega Rabies", "Steep drops" },
            "Ranged weapon and spare torches; watch the bat swarms.",
            "Decent crate spawns mid-route."),
        new("The Island", "South East Cave", "Massive", 70.6, 86.1, CaveDifficulty.Medium,
            new[] { "Lava", "Insects", "Bats" },
            "Careful footing beats firepower here; bring a grapple.",
            "Crates spawn on the lava ledges."),
        new("The Island", "North West Cave", "Skylord", 19.3, 19.0, CaveDifficulty.Medium,
            new[] { "Jump puzzle", "Bats", "Spiders" },
            "Grappling hooks trivialize the jump section.",
            "Crates tucked along the upper ledges."),
        new("The Island", "North East Cave", "Devourer", 14.7, 85.4, CaveDifficulty.Easy,
            new[] { "Bats", "Spiders" },
            "Light armor and a shotgun are plenty.",
            "Quick loop with steady crate spawns."),
        new("The Island", "Swamp Cave", "Immune", 62.7, 37.3, CaveDifficulty.Hard,
            new[] { "Toxic air", "High-level insects", "Heat" },
            "Gas mask is mandatory; a Beelzebufo shreds the bugs.",
            "Dense red-tier crate spawns."),
        new("The Island", "Snow Cave", "Strong", 29.1, 31.8, CaveDifficulty.Hard,
            new[] { "Extreme cold", "Purlovia ambushes", "Yetis" },
            "Fur plus fortitude on foot; nothing large fits inside.",
            "Some of the best crate loot on the map."),
        new("The Island", "Caverns of Lost Faith", "Brute", 53.9, 10.4, CaveDifficulty.Hard,
            new[] { "Underwater", "Sharks", "Electrophorus" },
            "Basilosaurus tank with scuba backup.",
            "Deep-sea crates near the artifact."),
        new("The Island", "Caverns of Lost Hope", "Cunning", 45.9, 88.9, CaveDifficulty.Hard,
            new[] { "Underwater", "Tusoteuthis", "Jellyfish" },
            "Basilosaurus or a strong Tuso; never swim it bare.",
            "Deep-sea crates in the main chamber."),
        new("The Island", "Tek Cave", null, 42.7, 39.2, CaveDifficulty.Hard,
            new[] { "Lava", "Gigas", "Entry timer" },
            "Boss trophies gate the door; bring end-game gear.",
            "The route to the Overseer arena."),

        // ===== The Center (9) =====
        new("The Center", "Lava Oasis Cave", "Hunter", 15.8, 50.5, CaveDifficulty.Medium,
            new[] { "Lava", "Insects", "Bats" },
            "Shotgun and repellant; mind the lava channels.",
            "Crates along the main loop."),
        new("The Center", "North Ice Cave", "Clever + Devourer", 18.7, 29.7, CaveDifficulty.Hard,
            new[] { "Extreme cold", "Predator packs" },
            "Fur set and a hardy mount for the approach.",
            "Two artifacts in one cold run."),
        new("The Center", "Lava Cave", "Massive + Strong", 11.2, 67.4, CaveDifficulty.Hard,
            new[] { "Lava", "Narrow ledges", "Insects" },
            "Grapples and patience; falls are the real killer.",
            "Two artifacts plus ledge crates."),
        new("The Center", "South Ice Cave", "Skylord", 60.0, 22.5, CaveDifficulty.Medium,
            new[] { "Cold", "Wolves", "Yetis" },
            "Fur armor and a shotgun handle it.",
            "Steady crate spawns."),
        new("The Center", "Jungle Cave", "Immune", 54.2, 62.7, CaveDifficulty.Medium,
            new[] { "Insects", "Water crossings" },
            "Repellant and a waterproof light source.",
            "Crates past the water sections."),
        new("The Center", "The Center Cave", "Devious", 35.9, 34.4, CaveDifficulty.Medium,
            new[] { "Underwater entrances", "Bats", "Spiders" },
            "Lazarus Chowder smooths the swim in.",
            "Crates beneath the floating island."),
        new("The Center", "Cliffside Cavern", "Cunning", 36.0, 2.0, CaveDifficulty.Medium,
            new[] { "Cliff entrance", "Snakes", "Spiders" },
            "Flyer to reach the mouth, then a standard cave kit.",
            "Crates near the artifact chamber."),
        new("The Center", "Underground World", "Pack", 34.9, 65.8, CaveDifficulty.Hard,
            new[] { "Easy to get lost", "Predators", "Underwater entry" },
            "Mark your route; bring a strong mount through the entry pool.",
            "A hidden biome with crates throughout."),
        new("The Center", "Southeastern Trench", "Brute", 69.1, 92.2, CaveDifficulty.Hard,
            new[] { "Deep water", "Sharks", "Jellyfish" },
            "Basilosaurus plus scuba; watch your depth.",
            "Deep-sea crates in the trench."),

        // ===== Scorched Earth (3) =====
        new("Scorched Earth", "Grave of the Tyrants", "Crag", 28.5, 29.4, CaveDifficulty.Hard,
            new[] { "Onyc swarms", "Arthropleura", "Heat" },
            "Shotgun, repellant, and plenty of water.",
            "Strong crate loot for the map."),
        new("Scorched Earth", "Old Tunnels", "Gatekeeper", 58.8, 47.9, CaveDifficulty.Medium,
            new[] { "Insects", "Bats", "Tight passages" },
            "Standard cave kit; keep hydration up.",
            "Crates through the central ruins."),
        new("Scorched Earth", "Ruins of Nosti", "Destroyer", 77.9, 75.7, CaveDifficulty.Medium,
            new[] { "Snakes", "Scorpions", "Heat" },
            "Desert gear plus a shotgun.",
            "Crates in the buried city."),

        // ===== Ragnarok (7) =====
        new("Ragnarok", "Jungle Dungeon", "Hunter", 18.6, 27.8, CaveDifficulty.Hard,
            new[] { "High-level spawns", "Water sections", "Lava Elemental arena" },
            "End-game gear; the optional elemental hits hard.",
            "Dungeon crates plus elemental drops."),
        new("Ragnarok", "Frozen Dungeon", "Pack", 30.9, 37.8, CaveDifficulty.Hard,
            new[] { "Extreme cold", "Iceworms", "Boss arena" },
            "Fur, fortitude, and ranged for the Iceworm Queen.",
            "The queen drops top-tier loot."),
        new("Ragnarok", "Carnivorous Caverns", "Cunning + Immune", 20.3, 45.9, CaveDifficulty.Hard,
            new[] { "Maze layout", "Insects", "Bats" },
            "Bring markers; two artifacts on one sprawling route.",
            "Crates scattered across the levels."),
        new("Ragnarok", "Life's Labyrinth", "Clever + Devious + Massive + Skylord", 51.6, 77.5, CaveDifficulty.Hard,
            new[] { "Traps", "Parkour", "Puzzles" },
            "Grapples, patience, and light gear for the trap runs.",
            "Four artifacts for one dungeon clear."),
        new("Ragnarok", "Fallen Redwood Cave", "Brute", 34.2, 79.1, CaveDifficulty.Medium,
            new[] { "Insects", "Tight squeezes" },
            "Standard cave kit on foot.",
            "The artifact sits inside the fallen trunk."),
        new("Ragnarok", "Sunken Ship Grotto", "Devourer", 47.3, 2.3, CaveDifficulty.Medium,
            new[] { "Underwater", "Sharks" },
            "Scuba or a quick dive mount.",
            "The artifact rests among the wrecks."),
        new("Ragnarok", "Monkey Temple Ruins", "Strong", 24.6, 25.0, CaveDifficulty.Easy,
            new[] { "Light puzzle" },
            "No real combat; just find the way in.",
            "A fast artifact grab."),

        // ===== Aberration (3) =====
        new("Aberration", "Old Railway Cave", "Depths", 48.3, 27.2, CaveDifficulty.Medium,
            new[] { "Darkness", "Ravagers", "Water" },
            "Charge light and a Ravager or shotgun.",
            "Crates along the old rails."),
        new("Aberration", "Hidden Grotto", "Shadows", 55.2, 65.9, CaveDifficulty.Hard,
            new[] { "Nameless", "Seekers", "Darkness" },
            "Keep a charge pet lit at all times.",
            "Blue-zone crates near the artifact."),
        new("Aberration", "Elemental Vault", "Stalker", 82.4, 48.2, CaveDifficulty.Hard,
            new[] { "Radiation", "Reapers", "Nameless" },
            "Hazmat suit, charge pet, and a strong shotgun.",
            "Red-zone loot; the highest risk on the map."),

        // ===== Extinction (3) =====
        new("Extinction", "Desert Cave", "Chaos", 87.4, 70.4, CaveDifficulty.Hard,
            new[] { "Corrupted creatures", "Tight tunnels" },
            "Velonasaur or good guns; ends at the Desert Titan terminal.",
            "Artifact plus titan terminal access."),
        new("Extinction", "Forest Cave", "Growth", 11.8, 39.3, CaveDifficulty.Hard,
            new[] { "Corrupted creatures", "Ambush spots" },
            "Strong shooters; ends at the Forest Titan terminal.",
            "Artifact plus titan terminal access."),
        new("Extinction", "Ice Cave", "Void", 20.3, 62.2, CaveDifficulty.Hard,
            new[] { "Extreme cold", "Corrupted creatures" },
            "Fur under armor; ends at the Ice Titan terminal.",
            "Artifact plus titan terminal access."),

        // ===== Valguero (6) =====
        new("Valguero", "The Lost Temple", "Brute + Devourer", 46.9, 87.5, CaveDifficulty.Medium,
            new[] { "Insects", "Bats", "Water" },
            "Standard cave kit; two artifacts per run.",
            "Crates through the temple halls."),
        new("Valguero", "The Lair", "Strong + Immune + Pack", 73.1, 40.6, CaveDifficulty.Hard,
            new[] { "Dense spawns", "Cramped tunnels" },
            "Shotgun and repellant; three artifacts inside.",
            "A rich crate route."),
        new("Valguero", "The Unknown", "Gatekeeper", 32.3, 92.4, CaveDifficulty.Hard,
            new[] { "Darkness", "Nameless", "Reapers" },
            "Charge light and hazard-ready gear for the trench.",
            "Aberrant-zone loot below the map."),
        new("Valguero", "Crag Lava Cave", "Crag", 33.5, 51.7, CaveDifficulty.Medium,
            new[] { "Lava", "Bats" },
            "Flyer to the entrance, then careful footing.",
            "The artifact waits in the lava chamber."),
        new("Valguero", "Snow Cave", "Cunning", 15.4, 27.3, CaveDifficulty.Medium,
            new[] { "Cold", "Predators" },
            "Fur set and a shotgun.",
            "The artifact hides behind the ramp room."),
        new("Valguero", "The Great Trench", "Skylord", 78.3, 90.4, CaveDifficulty.Hard,
            new[] { "Ice wyverns", "Underwater passage" },
            "Fast flyer in, then a short dive to the island.",
            "The artifact sits on a ledge island in the trench."),

        // ===== Crystal Isles (3) =====
        new("Crystal Isles", "Desert Wyvern Hive", "Devious", 74.8, 42.8, CaveDifficulty.Hard,
            new[] { "Crystal Wyverns" },
            "Fastest flyer you own; grab and go.",
            "The artifact sits inside the hive itself."),
        new("Crystal Isles", "Copper Peaks Plunge Pool", "Massive", 54.9, 52.1, CaveDifficulty.Easy,
            new[] { "Short dive" },
            "Dive at the waterfall base; no fight involved.",
            "The artifact rests under the falls."),
        new("Crystal Isles", "Emerald Plains Falls", "Skylord", 40.8, 43.7, CaveDifficulty.Easy,
            new[] { "Short dive" },
            "Swim down at the plunge pool.",
            "The artifact waits at the waterfall base."),

        // ===== Lost Island (10) =====
        new("Lost Island", "Aberrant Waterfall Cave", "Strong", 25.3, 54.9, CaveDifficulty.Hard,
            new[] { "Aberrant creatures", "Darkness", "Water" },
            "Charge light plus a shotgun behind the falls.",
            "An Aberration-style side biome."),
        new("Lost Island", "Sinkhole Cave", "Pack", 37.3, 32.7, CaveDifficulty.Medium,
            new[] { "Predators", "Steep drops" },
            "Rope down carefully; standard kit.",
            "The artifact sits near the waterfall sink."),
        new("Lost Island", "Northwest Cliff Cave", "Hunter", 36.5, 14.2, CaveDifficulty.Medium,
            new[] { "Insects", "Bats" },
            "Standard cave kit.",
            "A straightforward artifact route."),
        new("Lost Island", "Flooded Jungle Cave", "Clever", 25.4, 43.0, CaveDifficulty.Medium,
            new[] { "Underwater entrance", "Piranhas", "Sarcos" },
            "Clear the pool before you dive in.",
            "The artifact lies past the flooded entry."),
        new("Lost Island", "Desert Falls Cave", "Brute", 81.8, 82.7, CaveDifficulty.Medium,
            new[] { "Heat", "Predators" },
            "Desert gear; the entrance hides behind the waterfall.",
            "The artifact sits in the scorched biome."),
        new("Lost Island", "Pine Hollow Cave", "Cunning", 56.0, 70.4, CaveDifficulty.Medium,
            new[] { "Predators" },
            "The entrance sits behind the pines; a light kit works.",
            "A quick artifact run."),
        new("Lost Island", "Redwood Ridge Cave", "Immune", 25.3, 71.2, CaveDifficulty.Hard,
            new[] { "Dense spawns", "Tight passages" },
            "Shotgun and repellant.",
            "Crates along the deeper halls."),
        new("Lost Island", "Sunken Temple Caverns", "Devious + Massive", 58.9, 47.3, CaveDifficulty.Hard,
            new[] { "Maze layout", "Predators", "Water" },
            "A long shared system; mark your exits.",
            "Two artifacts in one network."),
        new("Lost Island", "Trenchside Cave", "Skylord", 58.4, 57.0, CaveDifficulty.Medium,
            new[] { "Wyverns nearby", "Steep drops" },
            "Slip past the trench traffic with a fast flyer.",
            "The artifact sits a short way inside."),
        new("Lost Island", "Sunken Ship Wreck", "Devourer", 78.5, 20.7, CaveDifficulty.Medium,
            new[] { "Underwater", "Sharks" },
            "Scuba dive down to the ruined hull.",
            "The artifact rests in the wreck."),

        // ===== Fjordur (11) =====
        new("Fjordur", "Drengrheimr Cave", "Hunter", 3.2, 32.6, CaveDifficulty.Medium,
            new[] { "Cold", "Predators" },
            "Fur and a shotgun for the north cave.",
            "Artifact plus crystal deposits."),
        new("Fjordur", "Bear Caverns", "Strong", 8.8, 24.5, CaveDifficulty.Medium,
            new[] { "Dire Bears", "Cold" },
            "Strong mount or shotgun; bears own the halls.",
            "The artifact waits deep in the den."),
        new("Fjordur", "The Frozen Fortress", "Skylord", 7.7, 23.5, CaveDifficulty.Hard,
            new[] { "Extreme cold", "Ice predators", "Maze halls" },
            "Full fur and fortitude for the ice castle.",
            "The artifact lies within the fortress depths."),
        new("Fjordur", "Mariana Caverns", "Devourer", 3.5, 3.7, CaveDifficulty.Hard,
            new[] { "Deep water", "Long swims" },
            "Basilosaurus or full scuba for the dive.",
            "The artifact sits in the deep-sea cavern."),
        new("Fjordur", "Skarstind Sea Cave", "Massive", 71.7, 1.1, CaveDifficulty.Hard,
            new[] { "Underwater entrance", "Predators" },
            "Dive in from the southwest coast.",
            "The artifact lies past the flooded entry."),
        new("Fjordur", "Snake Pit", "Brute", 49.4, 14.3, CaveDifficulty.Hard,
            new[] { "Toxic gas", "Snakes" },
            "Gas mask required on the swamp island.",
            "The artifact waits in the pit chamber."),
        new("Fjordur", "Molten Caverns", "Clever + Pack", 21.2, 57.4, CaveDifficulty.Hard,
            new[] { "Lava", "Heat", "Predators" },
            "Heat-resistant kit; two artifacts inside.",
            "Twin artifacts in one lava run."),
        new("Fjordur", "Runheimr Falls Cave", "Shadows", 10.0, 84.4, CaveDifficulty.Medium,
            new[] { "Water climb", "Predators" },
            "The entrance sits above the waterfall.",
            "The artifact hides in the forest cave."),
        new("Fjordur", "Broken Meadows Cave", "Stalker", 56.9, 84.9, CaveDifficulty.Hard,
            new[] { "Darkness", "Aberrant creatures" },
            "Charge light for the glowing tunnels.",
            "An Aberration-style artifact run."),
        new("Fjordur", "Forgotten Channel Cave", "Cunning", 77.0, 65.5, CaveDifficulty.Medium,
            new[] { "Partial swim", "Predators" },
            "Waterproof kit for the channel crossing.",
            "The artifact sits between the continents."),
        new("Fjordur", "Mount Doom Caverns", "Immune", 91.0, 78.0, CaveDifficulty.Hard,
            new[] { "Lava", "Extreme heat" },
            "Flak plus heat protection in the volcano.",
            "The artifact waits in the lava halls.")
    };
}
