name: Final Debug

on:
  release:
  push:
    tags:
      - '*'

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Something triggered this workflow"
      - run: echo "Event was ${{ github.event_name }}"
      - run: echo "Ref is ${{ github.ref }}"
