name: All Release Events

on:
  release:
    types: [published, unpublished, created, edited, deleted, prereleased, released]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Release event triggered!"
      - run: echo "Event type was ${{ github.event.action }}"
      - run: echo "Tag is ${{ github.event.release.tag_name }}"
