name: Release Test

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Release workflow triggered!"
      - run: echo "Tag is ${{ github.event.release.tag_name }}"
