name: Discord Release Notification

on:
  release:

jobs:
  notify:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Send Discord notification
        run: |
          curl -X POST "${{ secrets.DISCORD_WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            -d "{\"content\": \"🚀 **New Release:** ${{ github.event.release.tag_name }}\\n\\n**${{ github.event.release.name }}**\\n\\n${{ github.event.release.html_url }}\"}"
