name: Discord Release Notification

on:
  release:
    types: [published]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          args: |
            🚀 **New Release**: ${{ github.event.release.tag_name }}
            
            **${{ github.event.release.name }}**
            
            ${{ github.event.release.body }}
            
            [Download here](${{ github.event.release.html_url }})
