name: Notify Discord on Release

on:
  release:
    types: [published]

jobs:
  discord_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        uses: peter-evans/discord-webhook@v1
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            🎉 New Version Live ! **${{ github.event.release.tag_name }}** 
            Take a look here ${{ github.event.release.html_url }}
